// app/components/Footer.vue
<template>
  <nav class="bottom-nav">
    <NuxtLink active-class="active" class="link" href="/">/home</NuxtLink>
    <NuxtLink active-class="active" class="link" href="/projects">/projects</NuxtLink>
    <NuxtLink active-class="active" class="link" href="/uses">/uses</NuxtLink>
  </nav>
</template>

// app/_components/Footer.tsx
'use client'

import { usePathname } from 'next/navigation'
import Link from 'next/link'

export function Footer() {
  const pathname = usePathname()

  const getLinkStyle = (url: string) => {
    return `link${url === pathname ? ' active' : ''}`
  }

  return (
    <nav className="bottom-nav">
      <Link className={getLinkStyle('/')} href="/">/home</Link>
      {/* <Link className={getLinkStyle('/about')} href="/about">/about</Link> */}
      <Link className={getLinkStyle('/projects')} href="/projects">/projects</Link>
    </nav>
  )
}
